name = "cnproxypool"
pages_build_output_dir = "public"
compatibility_date = "2026-06-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "proxy_pool_hub"
database_id = "6a1be8ea-c3af-4ab1-b37f-f9a1db9d18e4"
